### ISSUE TITLE
NLinkify component throwing error in SSR

### ISSUE THREAD

**Issue by ursnj** [ursnj/nayan#13]
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6047:9)
    at renderNodeDestructiveImpl (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (/Users/nj/Desktop/projects/nayan/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6145:7)

**Comment by ursnj** [comment]
NLinkify component currently not supported in SSR, so please render that component only in local render, for Ex:

```
{typeof window !== 'undefined' && <NLinkify>www.nayanui.com</NLinkify>}
```
